env:
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    TOKEN: "ENCRYPTED[cb8f3f665d0fb335e3bf8d10ebe7c80c0a564f12924952dd20c3a2aa58193e29d0b3145fea698b5e641261399fa28f3d]"
    TG_CHAT_ID: "ENCRYPTED[38f66613fd9f1948693e5e0d6a9302cb65fb5728e1239837528e91adef6cdd2c526c9e470f988dd720a76bbcd4aa0e83]"
    PASSWORD: "ENCRYPTED[!0d19e31889f948190a8c998ab4c10d586d2b17cee888083d6c171c178bbe4dfa7db56377dd06101414ec0a46567d81a9!]"
    
task:
  name: "Kernel Pipeline"
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G
  
  Building_script:
      - git clone https://github.com/ShelbyHell/android_kernel_samsung_a31 q && cd q
      - gh auth login --with-token <<< "$PASSWORD"
      - git config --global user.email "shelbyhell@proton.me"
      - git config --global user.name "Alexey Shelby"
      - "ci=1 bash kramel.sh img mod mkzip"
