env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    TG_TOKEN: "ENCRYPTED[!362ad9c0bb2c607868a8282f612d9b1e75d06580a5a5872385347f53de088e93fc7337a53f9dcb146f9936d4de1afdfe!]"
    TG_CHAT_ID: "@SunriseCI"

task:
  name: "Kernel Build.."
  timeout_in: 1h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  SettingVM_script:
    - bash setting.sh
  
  Ahegao2_Building_script:
    - bash build_kernel_ahegao.sh