task:
  name: "Build Kernel for juice."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
    - bash test.sh
