env:
    TG_TOKEN: "ENCRYPTED[cb8f3f665d0fb335e3bf8d10ebe7c80c0a564f12924952dd20c3a2aa58193e29d0b3145fea698b5e641261399fa28f3d]"
    TG_CHAT_ID: "ENCRYPTED[38f66613fd9f1948693e5e0d6a9302cb65fb5728e1239837528e91adef6cdd2c526c9e470f988dd720a76bbcd4aa0e83]"
    RCLONE_CONF: "ENCRYPTED[!96cbdbaff1fd6c11dd1e40958fb7915fffc69d67132e96513e86c5f3ab59ee4d8a2161c35e6f92c26d58fc5dde2c72b3!]"

task:
  name: "TWRP build."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  SettingVM_script:
    - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Setup VM for building. Build2"
    - bash setting.sh
    - mkdir -p ~/.config/rclone
    - echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
  
  Ahegao2_Building_script:
   - bash finalochka.sh
