env:
    tltoken: "ENCRYPTED[!d49667b21877d02663f67cfb4bc5302091ada98612db7426602bab8637eb03d9f39e8c1f81ef2f5287a5a42973491c9e!]"
    tlchat: "@SunriseCI"

task:
  name: "Build Kernel for juice."
  timeout_in: 120m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
  
  SettingVM_script:
    - bash setting.sh
  
  Ahegao2_Building_script:
    - bash build_kernel_ahegao.sh
