env:
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    TG_TOKEN: "ENCRYPTED[cb8f3f665d0fb335e3bf8d10ebe7c80c0a564f12924952dd20c3a2aa58193e29d0b3145fea698b5e641261399fa28f3d]"
    TG_CHAT_ID: "@SunriseCI"

task:
  name: "Kernel Build.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Trigger_script:
    - curl -s https://api.telegram.org/${TG_TOKEN}/sendMessage -d chat_id=@SunriseCI -d text="Triggered start build on CirrusCI."

  SettingVM_script:
    - curl -s https://api.telegram.org/${TG_TOKEN}/sendMessage -d chat_id=@SunriseCI -d text="Setup VM for building Kernel."
    - bash setting.sh
  
  Ahegao2_Building_script:
    - echo "test build + tg posting"
    - curl -s https://api.telegram.org/${TG_TOKEN}/sendMessage -d chat_id=@SunriseCI -d text="test build + tg posting"
    - bash build_kernel_ahegao.sh

  sdm439_Building_script:
    - echo "test build + tg posting"
    - bash build_kernel_sdm439_ahegao.sh
